Spanish language update
dragomano/Light-Portal pull request #34
Opened 2021-09-26 03:11 UTC by RockLee-BC

I believe this is everything, anything will tell me :)

2021-09-26 04:06 UTC, dragomano requested changes

2021-09-26 04:06 UTC, dragomano commented on Themes/default/languages/LightPortal/.spanish_es.php
Compare with `.english.php` file in the **develop** branch

2021-09-26 14:18 UTC, RockLee-BC commented on Sources/LightPortal/addons/Likely/langs/spanish_es.php
> +		'viber' => 'Send',
Ops I overlooked it, my bad

2021-09-26 14:54 UTC, dragomano commented on Sources/LightPortal/addons/BoardIndex/langs/spanish_latin.php
> +  'allow_for_spiders' => 'Permitir la indexación de la página de inicio del foro',
There is still not enough tabs

2021-09-26 15:35 UTC, dragomano approved these changes
Good job, gracias :)

2021-09-26 15:49 UTC, RockLee-BC commented
no problem :D I see if I look at the documentation and translate, gran trabajo 👍

2021-09-27 08:24 UTC, dragomano commented
In any case, use develop branch of this repository to fetch the latest changes and to push your changes.

2021-09-28 15:56 UTC, merged